importjava.util.Scanner;
classCalculator
{
publicstaticvoidmain(String[]args)
{
Scanners=newScanner(System.in);
System.out.println("YOUHAVEFOLLOWINGCHOICES:");
System.out.println("1.ADDITION");
System.out.println("2.SUBTRACTION");
System.out.println("3.MULTIPLICATION");
System.out.println("4.DIVISION");
System.out.println("ENTERYOURCHOICE:");
inti=s.nextInt();
System.out.println("ENTERFIRSTNUMBER");
inta=s.nextInt();
System.out.println("ENTERSECONDNUMBER");
intb=s.nextInt();
doubleresult=0;//'result'willstoretheresultofoperation
switch(i)
{
case1:
result=a+b;
break;
case2:
result=a-b;
break;
case3:
result=a*b;
break;
case4:
if(b==0)//whendenominatorbecomeszero
{
System.out.println("DIVISIONNOTPOSSIBLE");
break;
}
else
result=a/b;.
default:
System.out.println("YOUHAVEENTEREDAWRONGCHOICE");
}
System.out.println("RESULT="+result);
}
}